// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56ZXEVqxOFqbP9PW_mpQqDPDi_GqwKQk',
    appId: '1:672231367520:web:1ef21f14b5f36a93bc3405',
    messagingSenderId: '672231367520',
    projectId: 'app-control-kinder',
    authDomain: 'app-control-kinder.firebaseapp.com',
    storageBucket: 'app-control-kinder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOn4udpc9dPSGuu4694iAll99irB2LjE',
    appId: '1:672231367520:android:4b928334892fe030bc3405',
    messagingSenderId: '672231367520',
    projectId: 'app-control-kinder',
    storageBucket: 'app-control-kinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg75Or7u8OiG1REEQs-UwhX9NCMPWNGJ0',
    appId: '1:672231367520:ios:d7167c03a55e33cfbc3405',
    messagingSenderId: '672231367520',
    projectId: 'app-control-kinder',
    storageBucket: 'app-control-kinder.firebasestorage.app',
    iosBundleId: 'com.example.appControlKinderV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg75Or7u8OiG1REEQs-UwhX9NCMPWNGJ0',
    appId: '1:672231367520:ios:d7167c03a55e33cfbc3405',
    messagingSenderId: '672231367520',
    projectId: 'app-control-kinder',
    storageBucket: 'app-control-kinder.firebasestorage.app',
    iosBundleId: 'com.example.appControlKinderV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA56ZXEVqxOFqbP9PW_mpQqDPDi_GqwKQk',
    appId: '1:672231367520:web:590b9d3bd69eb7cfbc3405',
    messagingSenderId: '672231367520',
    projectId: 'app-control-kinder',
    authDomain: 'app-control-kinder.firebaseapp.com',
    storageBucket: 'app-control-kinder.firebasestorage.app',
  );
}
